name: Shell command execution

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: echo given value
        run: echo "Hello world"
      - uses: ./.github/actions/docker-actions